export const SOCKET_EVENTS = {
  CUSTOMER_CREATED: 'customer:created',
  CUSTOMER_UPDATED: 'customer:updated',
  CUSTOMER_DELETED: 'customer:deleted',
  CUSTOMERS_BULK_DELETED: 'customers:bulk-deleted',
  APPOINTMENT_CREATED: 'appointment:created',
  APPOINTMENT_STATUS: 'appointment:status',
  APPOINTMENT_DELETED: 'appointment:deleted',
  APPOINTMENT_STARTED: 'appointment:started',
  APPOINTMENT_COMPLETED: 'appointment:completed',
  APPOINTMENT_POSTPONED: 'appointment:postponed',
  NOTIFICATION_NEW: 'notification:new',
  MESSAGE_NEW: 'message:new',
  AUDIT_NEW: 'audit:new',
  DM_NEW: 'dm:new',
  DM_DELETED: 'dm:deleted',
  AUDIT_DELETED: 'audit:deleted',
  CONFIG_UPDATED:    'config:updated',
  SETTINGS_UPDATED:  'settings:updated',
};
export const SOCKET_ROOMS = {
  ALL: 'all',
  ADMIN: 'ADMIN',
  SCHEDULING: 'SCHEDULING',
  TECHNICIAN: 'TECHNICIAN',
};
