import i18n from "i18next";
import { initReactI18next } from "react-i18next";
import LanguageDetector from "i18next-browser-languagedetector";

const ar: any = {
  common: { save:"حفظ",cancel:"إلغاء",delete:"حذف",edit:"تعديل",search:"بحث...",loading:"جاري التحميل...",error:"حدث خطأ",success:"تم بنجاح",yes:"نعم",no:"لا",close:"إغلاق",back:"رجوع",next:"التالي",add:"إضافة",view:"عرض",name:"الاسم",phone:"الجوال",notes:"ملاحظات",status:"الحالة",date:"التاريخ",actions:"الإجراءات",total:"الإجمالي",active:"نشط",inactive:"غير نشط",all:"الكل",noRecords:"لا توجد سجلات" },
  auth: { login:"تسجيل الدخول",logout:"تسجيل الخروج",email:"البريد الإلكتروني",password:"كلمة المرور",invalidCredentials:"بيانات الدخول غير صحيحة",serverUrl:"عنوان الخادم",serverSetup:"إعداد الخادم",connect:"اتصال",appName:"نظام صيانة فلاتر المياه",accessCode:"رمز الدخول",wrongCode:"رمز الدخول غير صحيح",enterCode:"أدخل رمز الدخول",back:"رجوع",enter:"دخول",connectingError:"تعذر الاتصال بالخادم" },
  nav: { dashboard:"لوحة التحكم",customers:"العملاء",appointments:"المواعيد",tasks:"المهام",technicians:"الفنيون",messages:"الرسائل",notifications:"الإشعارات",messaging:"المراسلة",settings:"الإعدادات",workQueue:"قائمة العمل",reports:"التقارير",accessCodes:"رموز الدخول" },
  dept: { admin:"الإدارة",scheduling:"الجدولة والصيانة",technician:"الفنيون",selectDept:"اختر القسم",adminFull:"الإدارة",schedulingFull:"الجدولة والصيانة",technicianFull:"الفنيون" },
  customers: { title:"العملاء",add:"إضافة عميل",edit:"تعديل العميل",maintenanceCycle:"دورة الصيانة",daily:"يومي",weekly:"أسبوعي",monthly:"شهري",frequency:"التكرار",city:"المدينة",district:"الحي",street:"الشارع",postalCode:"الرمز البريدي",buildingNo:"رقم المبنى",floorNo:"رقم الطابق",apartmentNo:"رقم الشقة",address:"العنوان",phoneInvalid:"رقم الجوال يجب أن يبدأ بـ 05 ويتكون من 10 أرقام",toggleActive:"تبديل الحالة",deleteCustomer:"حذف العميل",deleteConfirm:"هل أنت متأكد من حذف:",deleteWarning:"سيؤدي ذلك إلى حذف جميع المواعيد والمهام والسجل المرتبط بهذا العميل نهائياً.",yesDelete:"نعم، احذف",deleting:"جاري الحذف...",deleted:"تم حذف العميل",every:"كل",days:"أيام",weeks:"أسابيع",months:"أشهر",day:"يوم",week:"أسبوع",month:"شهر",enterNotes:"أدخل ملاحظات تفصيلية حول هذا العميل...",deleteAll:"حذف جميع العملاء",allDeleted:"تم حذف جميع العملاء",deleteAllTitle:"حذف جميع العملاء",willBeDeleted:"عميل سيتم حذفه",deleteAllWarning:"هذا الإجراء لا يمكن التراجع عنه. سيتم حذف جميع العملاء والمواعيد والمهام المرتبطة بهم نهائياً.",typeDeleteToConfirm:"اكتب DELETE للتأكيد",deleteAllConfirmBtn:"نعم، احذف الجميع" },
  appointments: { title:"المواعيد",new:"موعد جديد",type:"النوع",installation:"تركيب",maintenance:"صيانة",scheduled:"مجدول",rescheduled:"معاد جدولته",cancelled:"ملغي",pending:"قيد الانتظار",customer:"العميل",technician:"الفني",selectCustomer:"اختر عميل" },
  tasks: { title:"المهام",approve:"موافقة",reject:"رفض",start:"بدء",complete:"إتمام",postpone:"تأجيل",reason:"السبب",newDate:"التاريخ الجديد",pendingApproval:"بانتظار الموافقة",approved:"تمت الموافقة",inProgress:"قيد التنفيذ",completed:"مكتملة",postponed:"مؤجلة",selectTechnician:"اختر فني",confirmComplete:"تأكيد إتمام المهمة",confirmPostpone:"تأكيد تأجيل المهمة",allCompleted:"جميع المهام مكتملة" },
  technicians: { title:"الفنيون",completedTasks:"المهام المكتملة",pendingTasks:"المهام المعلقة" },
  messages: { title:"سجل النشاط",placeholder:"اكتب رسالة...",send:"إرسال",systemActivityLog:"سجل نشاط النظام",liveUpdates:"تحديثات مباشرة من جميع الأقسام",noActivity:"لا يوجد نشاط مسجل بعد.",activityEvents:"ستظهر الأحداث هنا عند تنفيذ الإجراءات عبر الأقسام.",loadingActivity:"جاري تحميل النشاط...",deleteAll:"حذف الكل",deleteConfirm:"هل أنت متأكد من حذف هذا السجل؟",deleteAllConfirm:"هل أنت متأكد من حذف جميع سجلات النشاط؟",deleted:"تم الحذف",deletedAll:"تم حذف جميع السجلات" },
  notifications: { title:"الإشعارات",markAllRead:"تعيين الكل كمقروء",noNotifications:"لا توجد إشعارات",maintenanceReminders:"تذكيرات الصيانة",upcomingNotice:"صيانة قادمة — إشعار مسبق بـ 10 أيام",noReminders:"لا توجد تذكيرات قادمة.",remindersInfo:"يتم إرسال التذكيرات قبل 10 أيام من المواعيد المجدولة." },
  dashboard: { title:"لوحة التحكم",totalTasks:"إجمالي المهام",completedTasks:"المهام المكتملة",thisMonth:"هذا الشهر",nextMonth:"الشهر القادم",pendingTasks:"المهام المعلقة",activeCustomers:"العملاء النشطون",pendingApproval:"بانتظار الموافقة",recentActivity:"النشاط الأخير",customers:"العملاء",completedMaintenance:"الصيانة المكتملة",suspendedPostponed:"موقوف / مؤجل",overdueMaintenance:"الصيانة المتأخرة",dueToday:"الصيانة اليوم",clearAll:"مسح الكل",clearAllConfirm:"مسح كل النشاط؟",clearAllDesc:"سيتم إخفاء جميع سجلات النشاط الأخير. لا يمكن التراجع عن ذلك.",noRecentActivity:"لا يوجد نشاط حديث",clickToView:"انقر للعرض ←",noRecords:"لا توجد سجلات",cleared:"تم مسح النشاط",search:"بحث...",loading:"جاري التحميل..." },
  messaging: { inbox:"الوارد",sent:"المرسل",newMessage:"✉ رسالة جديدة",sendTo:"إرسال إلى",message:"الرسالة",typeMessage:"اكتب رسالتك...",sendMessage:"إرسال الرسالة",sending:"جاري الإرسال...",messageSent:"تم إرسال الرسالة",sendFailed:"فشل إرسال الرسالة",noInbox:"لم تصل رسائل بعد",noSent:"لم تُرسل رسائل بعد",newIndicator:"• جديد",conversations:"المحادثات",noConversations:"لا توجد محادثات بعد",deleteConversation:"حذف المحادثة",deleteAllConversations:"حذف جميع المحادثات",deleteConvConfirm:"هل أنت متأكد من حذف هذه المحادثة؟",deleteAllConvConfirm:"هل أنت متأكد من حذف جميع المحادثات؟",conversationWith:"محادثة مع",reply:"إرسال الرد",newConversation:"+ رسالة جديدة",deleted:"تم الحذف",deletedAll:"تم حذف جميع المحادثات" },
  scheduling: { scheduleMaintenance:"جدولة صيانة",viewHistory:"السجل",scheduleDate:"تاريخ الصيانة",maintenanceHistory:"سجل الصيانة",scheduledSuccess:"تم جدولة الصيانة بنجاح",noHistory:"لا يوجد سجل صيانة",lastMaintenance:"آخر صيانة",nextMaintenance:"الصيانة القادمة",noNext:"لم تُجدَّل بعد",noLast:"لم تُنجز صيانة" },
  roles: { ADMIN:"الإدارة",SCHEDULING:"الجدولة والصيانة",TECHNICIAN:"الفنيون" },
  time: { justNow:"الآن",minutesAgo:"{{count}} د",hoursAgo:"{{count}} س" },
  reports: { title:"التقارير",customerReports:"تقارير العملاء",dateFrom:"من تاريخ",dateTo:"إلى تاريخ",statusFilter:"تصفية حسب الحالة",allStatuses:"جميع الحالات",statusCompleted:"صيانة مكتملة",statusOverdue:"صيانة متأخرة",statusUpcoming:"صيانة قادمة (30 يوم)",statusPostponed:"مؤجل",statusThisMonth:"هذا الشهر",statusNextMonth:"الشهر القادم",exportPdf:"تصدير PDF",exportExcel:"تصدير Excel",exportCustPdf:"PDF",generating:"جاري الإنشاء...",savedTo:"تم الحفظ في التنزيلات",noResults:"لا توجد نتائج بهذه الفلاتر",reportTitle:"تقرير العملاء",registrationDate:"تاريخ التسجيل",lastMaintenance:"آخر صيانة",nextMaintenance:"الصيانة القادمة",maintenanceStatus:"حالة الصيانة",showingCount:"عرض {{count}} عميل",daysUntil:"أيام متبقية",exportCustomerPdf:"تصدير PDF للعميل" },
  countdown: { dueIn:"متبقي {{days}} يوم",dueToday:"الصيانة اليوم",dueTomorrow:"الصيانة غداً",overdueBy:"متأخر {{days}} يوم",noSchedule:"غير مجدول" },
  accessCodes: { title:"إدارة رموز الدخول",subtitle:"إدارة رموز الدخول لجميع الأقسام",adminDept:"قسم الإدارة",schedulingDept:"قسم الجدولة والصيانة",technicianDept:"قسم الفنيين",deptCodeDesc:"رمز الدخول المكون من 4 أرقام لهذا القسم",securityNote:"للتغيير يجب إدخال الرمز الحالي أولاً. تصبح الرموز الجديدة سارية فور الحفظ ولن يعمل الرمز القديم.",save:"حفظ",saveAll:"حفظ الجميع",codeSaved:"تم حفظ رمز الدخول",allSaved:"تم حفظ جميع الرموز",unsaved:"غير محفوظ",unsavedChanges:"لديك تعديلات غير محفوظة",mustBe4Digits:"يجب أن يكون الرمز 4 أرقام بالضبط",codesUpdatedRemotely:"تم تحديث رموز الدخول",currentCode:"الرمز الحالي",newCode:"الرمز الجديد",confirmCode:"تأكيد الرمز الجديد",updateCode:"تحديث الرمز",updateSuccess:"تم تحديث رمز الدخول بنجاح",errRequired:"هذا الحقل مطلوب",errMismatch:"الرمز الجديد وتأكيده غير متطابقين",errWrongCurrent:"الرمز الحالي غير صحيح. يرجى المحاولة مجدداً." },
};

const en: any = {
  common: { save:"Save",cancel:"Cancel",delete:"Delete",edit:"Edit",search:"Search...",loading:"Loading...",error:"An error occurred",success:"Success",yes:"Yes",no:"No",close:"Close",back:"Back",next:"Next",add:"Add",view:"View",name:"Name",phone:"Phone",notes:"Notes",status:"Status",date:"Date",actions:"Actions",total:"Total",active:"Active",inactive:"Inactive",all:"All",noRecords:"No records found" },
  auth: { login:"Login",logout:"Logout",email:"Email",password:"Password",invalidCredentials:"Invalid credentials",serverUrl:"Server URL",serverSetup:"Server Setup",connect:"Connect",appName:"Water Filter Maintenance System",accessCode:"Access Code",wrongCode:"Wrong access code",enterCode:"Enter Access Code",back:"Back",enter:"Enter",connectingError:"Cannot connect to server" },
  nav: { dashboard:"Dashboard",customers:"Customers",appointments:"Appointments",tasks:"Tasks",technicians:"Technicians",messages:"Messages",notifications:"Notifications",messaging:"Messaging",settings:"Settings",workQueue:"Work Queue",reports:"Reports",accessCodes:"Access Codes" },
  dept: { admin:"Administration",scheduling:"Scheduling & Maintenance",technician:"Technicians",selectDept:"Select Department",adminFull:"Administration",schedulingFull:"Scheduling & Maintenance",technicianFull:"Technicians" },
  customers: { title:"Customers",add:"Add Customer",edit:"Edit Customer",maintenanceCycle:"Maintenance Cycle",daily:"Daily",weekly:"Weekly",monthly:"Monthly",frequency:"Frequency",city:"City",district:"District",street:"Street",postalCode:"Postal Code",buildingNo:"Building No",floorNo:"Floor No",apartmentNo:"Apartment No",address:"Address",phoneInvalid:"Phone must start with 05 and be 10 digits",toggleActive:"Toggle Status",deleteCustomer:"Delete Customer",deleteConfirm:"Are you sure you want to delete:",deleteWarning:"This will permanently remove all appointments, tasks, and history linked to this customer.",yesDelete:"Yes, Delete",deleting:"Deleting...",deleted:"Customer deleted",every:"Every",days:"Days",weeks:"Weeks",months:"Months",day:"Day",week:"Week",month:"Month",enterNotes:"Enter detailed notes about this customer...",deleteAll:"Delete All Customers",allDeleted:"All customers deleted",deleteAllTitle:"Delete All Customers",willBeDeleted:"customer(s) will be deleted",deleteAllWarning:"This action cannot be undone. All customers, appointments, and linked tasks will be permanently removed.",typeDeleteToConfirm:'Type "DELETE" to confirm',deleteAllConfirmBtn:"Yes, Delete All" },
  appointments: { title:"Appointments",new:"New Appointment",type:"Type",installation:"Installation",maintenance:"Maintenance",scheduled:"Scheduled",rescheduled:"Rescheduled",cancelled:"Cancelled",pending:"Pending",customer:"Customer",technician:"Technician",selectCustomer:"Select Customer" },
  tasks: { title:"Tasks",approve:"Approve",reject:"Reject",start:"Start",complete:"Complete",postpone:"Postpone",reason:"Reason",newDate:"New Date",pendingApproval:"Pending Approval",approved:"Approved",inProgress:"In Progress",completed:"Completed",postponed:"Postponed",selectTechnician:"Select Technician",confirmComplete:"Confirm Complete Task",confirmPostpone:"Confirm Postpone Task",allCompleted:"All tasks completed" },
  technicians: { title:"Technicians",completedTasks:"Completed Tasks",pendingTasks:"Pending Tasks" },
  messages: { title:"Activity Log",placeholder:"Type a message...",send:"Send",systemActivityLog:"System Activity Log",liveUpdates:"Live updates from all departments",noActivity:"No activity recorded yet.",activityEvents:"Events will appear here as actions are performed across departments.",loadingActivity:"Loading activity...",deleteAll:"Delete All",deleteConfirm:"Delete this activity record?",deleteAllConfirm:"Delete all activity records?",deleted:"Deleted",deletedAll:"All records deleted" },
  notifications: { title:"Notifications",markAllRead:"Mark All Read",noNotifications:"No notifications",maintenanceReminders:"Maintenance Reminders",upcomingNotice:"Upcoming maintenance — 10 days advance notice",noReminders:"No upcoming reminders.",remindersInfo:"Reminders are sent 10 days before scheduled appointments." },
  dashboard: { title:"Dashboard",totalTasks:"Total Tasks",completedTasks:"Completed Tasks",thisMonth:"This Month",nextMonth:"Next Month",pendingTasks:"Pending Tasks",activeCustomers:"Active Customers",pendingApproval:"Pending Approval",recentActivity:"Recent Activity",customers:"Customers",completedMaintenance:"Completed Maintenance",suspendedPostponed:"Suspended / Postponed",overdueMaintenance:"Overdue Maintenance",dueToday:"Due Today",clearAll:"Clear All",clearAllConfirm:"Clear All Activity?",clearAllDesc:"All recent activity records will be hidden. This cannot be undone.",noRecentActivity:"No recent activity",clickToView:"Click to view →",noRecords:"No records found",cleared:"Activity cleared",search:"Search...",loading:"Loading..." },
  messaging: { inbox:"Inbox",sent:"Sent",newMessage:"✉ New Message",sendTo:"Send To",message:"Message",typeMessage:"Type your message...",sendMessage:"Send Message",sending:"Sending...",messageSent:"Message sent",sendFailed:"Failed to send message",noInbox:"No messages received yet",noSent:"No messages sent yet",newIndicator:"• New",conversations:"Conversations",noConversations:"No conversations yet",deleteConversation:"Delete Conversation",deleteAllConversations:"Delete All Conversations",deleteConvConfirm:"Delete this conversation?",deleteAllConvConfirm:"Delete all conversations?",conversationWith:"Conversation with",reply:"Send Reply",newConversation:"+ New Message",deleted:"Deleted",deletedAll:"All conversations deleted" },
  scheduling: { scheduleMaintenance:"Schedule",viewHistory:"History",scheduleDate:"Maintenance Date",maintenanceHistory:"Maintenance History",scheduledSuccess:"Maintenance scheduled successfully",noHistory:"No maintenance history",lastMaintenance:"Last Maintenance",nextMaintenance:"Next Maintenance",noNext:"Not scheduled yet",noLast:"No maintenance done" },
  roles: { ADMIN:"Administration",SCHEDULING:"Scheduling & Maintenance",TECHNICIAN:"Technicians" },
  time: { justNow:"Just now",minutesAgo:"{{count}}m ago",hoursAgo:"{{count}}h ago" },
  reports: { title:"Reports",customerReports:"Customer Reports",dateFrom:"From Date",dateTo:"To Date",statusFilter:"Filter by Status",allStatuses:"All Statuses",statusCompleted:"Completed Maintenance",statusOverdue:"Overdue Maintenance",statusUpcoming:"Upcoming (30 days)",statusPostponed:"Postponed",statusThisMonth:"This Month",statusNextMonth:"Next Month",exportPdf:"Export PDF",exportExcel:"Export Excel",exportCustPdf:"PDF",generating:"Generating...",savedTo:"Saved to Downloads",noResults:"No results for these filters",reportTitle:"Customer Report",registrationDate:"Reg. Date",lastMaintenance:"Last Maintenance",nextMaintenance:"Next Maintenance",maintenanceStatus:"Status",showingCount:"Showing {{count}} customers",daysUntil:"Days Until",exportCustomerPdf:"Export Customer PDF" },
  countdown: { dueIn:"Due in {{days}} days",dueToday:"Due today",dueTomorrow:"Due tomorrow",overdueBy:"Overdue by {{days}} days",noSchedule:"Not scheduled" },
  accessCodes: { title:"Access Code Management",subtitle:"Manage login codes for all departments",adminDept:"Administration Department",schedulingDept:"Scheduling & Maintenance Department",technicianDept:"Technician Department",deptCodeDesc:"4-digit access code for this department",securityNote:"You must enter the current code to make changes. New codes take effect immediately — the old code will no longer work.",save:"Save",saveAll:"Save All",codeSaved:"Access code updated",allSaved:"All codes saved",unsaved:"Unsaved",unsavedChanges:"You have unsaved changes",mustBe4Digits:"Code must be exactly 4 digits",codesUpdatedRemotely:"Access codes were updated remotely",currentCode:"Current Code",newCode:"New Code",confirmCode:"Confirm New Code",updateCode:"Update Code",updateSuccess:"Access code updated successfully",errRequired:"This field is required",errMismatch:"New code and confirmation do not match",errWrongCurrent:"Current code is incorrect. Please try again." },
};

i18n.use(LanguageDetector).use(initReactI18next).init({
  resources: { ar: { translation: ar }, en: { translation: en } },
  fallbackLng: "ar", lng: "ar",
  interpolation: { escapeValue: false }
});
i18n.on("languageChanged", lng => {
  document.documentElement.dir = lng === "ar" ? "rtl" : "ltr";
  document.documentElement.lang = lng;
});
export default i18n;